title: Miox
subtitle: "Modern Infrastructure Of Complex SPA"
description: "Miox is a fast, simple & powerful router/middleware framework run on web."
author: 沈赟杰
language: en
timezone: UTC

url: https://51nb.github.io/miox-doc
root: /miox-doc/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:51nb/miox-doc.git

highlight:
  enable: true
  line_number: false

github: 51nb/miox
